#!/bin/bash

python ~/master_thesis/3D_Pose_Estimation/main.py <--suffix pc20_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc30_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc40_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc50_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc60_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc70_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc80_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc90_cp50 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.lidar_projection_ratio, 0.5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc20_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc30_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc40_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc50_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc60_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc70_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc80_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc90_cp60 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.lidar_projection_ratio, 0.6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc20_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc30_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc40_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc50_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc60_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc70_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc80_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc90_cp70 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.lidar_projection_ratio, 0.7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc20_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc30_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc40_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc50_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc60_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc70_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc80_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc90_cp80 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.lidar_projection_ratio, 0.8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin


python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc20_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc30_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc40_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc50_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc60_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc70_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc80_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc90_cp90 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.lidar_projection_ratio, 0.9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc20_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc30_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc40_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc50_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc60_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc70_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc80_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --suffix pc90_cp100 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.lidar_projection_ratio, 1.0" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
