#!/bin/bash

python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nj4 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 4" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nj5 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 5" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nj6 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 6" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nj7 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 7" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin


python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nnj8 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 8" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin

python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nj9 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 9" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin


python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc20_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 20, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc30_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 30, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc40_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 40, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc50_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 50, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc60_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 60, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc70_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 70, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc80_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 80, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
python ~/master_thesis/3D_Pose_Estimation/main.py --dataset waymo_2d_labels_supervised --suffix pc90_nj10 --wandb True --wandb_project "pc_projectionratio_numpoints" --overwrite_gin_args "WaymoOpenDataset.pc_min_size, 90, WaymoOpenDataset.min_2D_keypoints, 10" --config /lhome/petbau/master_thesis/3D_Pose_Estimation/configs/config.gin
